server:
  port: 8453
logging:
  file: /java/C2S_LOGS/pls/pls.log
info:
  component: Provider Lookup Service
spring:
  datasource:
    # configure url, username and password per environment
    url: jdbc:mysql://localhost:3306/pls?autoReconnect=true
    username: root
    password: admin
  data:
    rest:
      default-page-size: 10
---
# updates configuration for docker environment
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${C2S_DB_HOST:pls-db.c2s.com}:${C2S_DB_PORT:3306}/pls?autoReconnect=true